### ISSUE TITLE
Action publication error `fatal: unable to access 'https://github.com/gabrielbdornas/code/': The requested URL returned error: 403`

### ISSUE THREAD

**Issue by gabrielbdornas** [gabrielbdornas/code#1]
```
Run mkdocs gh-deploy
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/runner/work/code/code/site
INFO    -  Documentation built in 0.62 seconds
WARNING -  Version check skipped: No version specified in previous deployment.
INFO    -  Copying '/home/runner/work/code/code/site' to 'gh-pages' branch and pushing to GitHub.
remote: Permission to gabrielbdornas/code.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/gabrielbdornas/code/': The requested URL returned error: 403
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 115[7](https://github.com/gabrielbdornas/code/actions/runs/9506710705/job/26204556154#step:6:8), in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 107[8](https://github.com/gabrielbdornas/code/actions/runs/9506710705/job/26204556154#step:6:9), in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs/__main__.py", line 314, in gh_deploy_command
    gh_deploy.gh_deploy(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs/commands/gh_deploy.py", line 12[9](https://github.com/gabrielbdornas/code/actions/runs/9506710705/job/26204556154#step:6:10), in gh_deploy
    ghp_import.ghp_import(
  File "/opt/hostedtoolcache/Python/3.[10](https://github.com/gabrielbdornas/code/actions/runs/9506710705/job/26204556154#step:6:11).2/x64/lib/python3.10/site-packages/ghp_import.py", line 285, in ghp_import
    git.check_call('push', opts['remote'], opts['branch'])
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/ghp_import.py", line [11](https://github.com/gabrielbdornas/code/actions/runs/9506710705/job/26204556154#step:6:12)9, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages']' returned non-zero exit status [12](https://github.com/gabrielbdornas/code/actions/runs/9506710705/job/26204556154#step:6:13)8.
Error: Process completed with exit code 1.
```

![image](https://github.com/gabrielbdornas/code/assets/49699290/b02d0633-1a16-4c8f-9357-ebac03b91bcf)

![image](https://github.com/gabrielbdornas/code/assets/49699290/c21ed2db-4759-42b6-8487-fe4101478aa9)

**Comment by gabrielbdornas** [comment]
Just put `Read and write permissions` in actions settings configurations:

![image](https://github.com/gabrielbdornas/code/assets/49699290/28a62d4f-9dd0-4c19-bbab-7eb93ba15222)

Obs.: No GitHub token is needed as this is a public repository.
